# Generated by Django 4.2.5 on 2023-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("UserID", models.AutoField(primary_key=True, serialize=False)),
                ("MobileNumber", models.CharField(max_length=15, unique=True)),
                ("Rabbi", models.CharField(max_length=100)),
                ("Kashrut", models.CharField(max_length=200)),
            ],
        ),
    ]
