# code generated by GPT4
# explanation is that I  need  the dict pending_requests_count to be
# available in any html  template and I can do this by registering
# this procesor in settings.py  
from .models import Booking

def pending_requests_count(request):
    if request.user.is_authenticated:
        count = Booking.objects.filter(property__owner=request.user, status='pending').count()
        return {'pending_requests_count': count}
    return {}

def your_next_escapes_count(request):
    if request.user.is_authenticated:
        count = Booking.objects.filter(property__owner=request.user, status='accepted').count()
        return {'your_next_escapes_count': count}
    return {}