# Generated by Django 4.2.5 on 2023-10-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kswap", "0003_profile_alter_property_owner_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property", name="city", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(max_length=50),
        ),
    ]
