# Generated by Django 4.2.5 on 2023-10-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kswap", "0004_alter_property_city_alter_property_property_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="proximity_to_public_transport",
            field=models.PositiveIntegerField(),
        ),
    ]
