# Generated by Django 4.2.5 on 2023-10-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kswap", "0004_alter_property_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=30),
        ),
    ]
