# Generated by Django 4.2.5 on 2023-10-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kswap", "0005_alter_property_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="property", name="accessibility_features",),
        migrations.RemoveField(model_name="property", name="amenities",),
        migrations.RemoveField(model_name="property", name="nearby_attractions",),
    ]
